# Generated by Django 4.0.3 on 2022-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='add',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
